name: linear_regression_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - jupyterlab
  - notebook
  - r-base>=4.3
  - r-irkernel
  - r-ggplot2
  - pip
